name: Full Frontend & Backend Lint & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - run: npm install -g htmlhint stylelint@15 eslint@8 stylelint-config-standard

      - run: htmlhint "frontend/**/*.html"

      - run: stylelint "frontend/**/*.css" || echo "CSS linting done"

      - run: eslint "frontend/**/*.js" || echo "JS linting done"

  backend:
    name: Lint & Test Backend
    runs-on: ubuntu-latest
    needs: frontend

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - run: |
          cd backend
          npm install

      - run: |
          cd backend
          npm install eslint@8 --save-dev
          npx eslint . --ext .js || echo "Backend JS lint done"

      - run: |
          cd backend
          if npm run | grep -q "test"; then
            # check if test script is just the default "no test specified"
            TEST_SCRIPT=$(node -p "require('./package.json').scripts?.test || ''")
            if [[ "$TEST_SCRIPT" == *"no test specified"* ]]; then
              echo "Default test script found, skipping tests"
            else
              npm test
            fi
          else
            echo "No test script found, skipping tests"
          fi
