name: Full Lint & Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Global Linters
        run: |
          npm install -g htmlhint stylelint eslint stylelint-config-standard

      - name: Lint HTML
        run: htmlhint "frontend/**/*.html"

      - name: Lint CSS
        run: stylelint "frontend/**/*.css" || echo "CSS linting done"

      - name: Lint JS
        run: eslint "frontend/**/*.js" || echo "JS linting done"

  backend:
    name: Lint & Test Backend
    runs-on: ubuntu-latest
    needs: frontend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Lint Backend JS
        run: |
          cd backend
          npx eslint . --ext .js

      - name: Run Backend Tests
        run: |
          cd backend
          npm test
